/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Tiang001: THREE.Mesh
  }
  materials: {
    ['Material.176']: THREE.MeshStandardMaterial
  }
}

export function Pole3(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/fast-car/models/environments/Pole3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Tiang001.geometry}
        material={materials['Material.176']}
        position={[498.339, 6.973, 250.215]}
        rotation={[0, -0.117, 0]}
        scale={[1, 6, 1]}
      />
    </group>
  )
}

useGLTF.preload('/games/fast-car/models/environments/Pole3.glb')
