/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
  }
  materials: {
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.133']: THREE.MeshStandardMaterial
    ['Material.134']: THREE.MeshStandardMaterial
  }
}

export function PoleStart(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/fast-car/models/environments/TiangStart.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-380, 6.973, 1201]} rotation={[0, 0.067, 0]} scale={[1, 6, 1]}>
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials['Material.073']}
        />
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials['Material.133']}
        />
        <mesh
          geometry={nodes.Cube005_2.geometry}
          material={materials['Material.134']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/fast-car/models/environments/TiangStart.glb')
