/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cube024_3: THREE.Mesh
    Cube024_4: THREE.Mesh
    Cube024_5: THREE.Mesh
    Cube024_6: THREE.Mesh
    Cube024_7: THREE.Mesh
  }
  materials: {
    ['Material.142']: THREE.MeshStandardMaterial
    ['Material.143']: THREE.MeshStandardMaterial
    ['Material.136']: THREE.MeshStandardMaterial
    ['Material.137']: THREE.MeshStandardMaterial
    ['Material.138']: THREE.MeshStandardMaterial
    ['Material.139']: THREE.MeshStandardMaterial
    ['Material.140']: THREE.MeshStandardMaterial
    ['Material.141']: THREE.MeshStandardMaterial
  }
}

export function Tribune(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/fast-car/models/environments/Tribune.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[493.955, 1.741, 1123.457]} rotation={[0, -0.36, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={materials['Material.142']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_1.geometry}
          material={materials['Material.143']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_2.geometry}
          material={materials['Material.136']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_3.geometry}
          material={materials['Material.137']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_4.geometry}
          material={materials['Material.138']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_5.geometry}
          material={materials['Material.139']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_6.geometry}
          material={materials['Material.140']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_7.geometry}
          material={materials['Material.141']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/fast-car/models/environments/Tribune.glb')
