/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube064: THREE.Mesh
    Cube064_1: THREE.Mesh
    Cube064_2: THREE.Mesh
    Cube064_3: THREE.Mesh
    Cube064_4: THREE.Mesh
    Cube064_5: THREE.Mesh
    Cube064_6: THREE.Mesh
  }
  materials: {
    ['Material.333']: THREE.MeshStandardMaterial
    ['Material.320']: THREE.MeshStandardMaterial
    ['Material.328']: THREE.MeshStandardMaterial
    ['Material.329']: THREE.MeshStandardMaterial
    ['Material.330']: THREE.MeshStandardMaterial
    ['Material.331']: THREE.MeshStandardMaterial
    ['Material.332']: THREE.MeshStandardMaterial
  }
}

export function Apart1(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/apart1.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064.geometry}
        material={materials['Material.333']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064_1.geometry}
        material={materials['Material.320']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064_2.geometry}
        material={materials['Material.328']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064_3.geometry}
        material={materials['Material.329']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064_4.geometry}
        material={materials['Material.330']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064_5.geometry}
        material={materials['Material.331']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064_6.geometry}
        material={materials['Material.332']}
      />
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/apart1.glb')
