/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube069: THREE.Mesh
    Cube069_1: THREE.Mesh
    Cube069_2: THREE.Mesh
    Cube069_3: THREE.Mesh
    Cube069_4: THREE.Mesh
    Cube069_5: THREE.Mesh
    Cube069_6: THREE.Mesh
  }
  materials: {
    ['Material.347']: THREE.MeshStandardMaterial
    ['Material.348']: THREE.MeshStandardMaterial
    ['Material.349']: THREE.MeshStandardMaterial
    ['Material.350']: THREE.MeshStandardMaterial
    ['Material.351']: THREE.MeshStandardMaterial
    ['Material.353']: THREE.MeshStandardMaterial
    ['Material.356']: THREE.MeshStandardMaterial
  }
}

export function Apart3(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/apart3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials['Material.347']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069_1.geometry}
        material={materials['Material.348']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069_2.geometry}
        material={materials['Material.349']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069_3.geometry}
        material={materials['Material.350']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069_4.geometry}
        material={materials['Material.351']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069_5.geometry}
        material={materials['Material.353']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069_6.geometry}
        material={materials['Material.356']}
      />
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/apart3.glb')
