/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube062: THREE.Mesh
    Cube062_1: THREE.Mesh
    Cube062_2: THREE.Mesh
    Cube062_3: THREE.Mesh
    Cube062_4: THREE.Mesh
    Cube062_5: THREE.Mesh
    Cube062_6: THREE.Mesh
    Cube062_7: THREE.Mesh
  }
  materials: {
    ['Material.340']: THREE.MeshStandardMaterial
    ['Material.341']: THREE.MeshStandardMaterial
    ['Material.342']: THREE.MeshStandardMaterial
    ['Material.343']: THREE.MeshStandardMaterial
    ['Material.344']: THREE.MeshStandardMaterial
    ['Material.345']: THREE.MeshStandardMaterial
    ['Material.346']: THREE.MeshStandardMaterial
    ['Material.355']: THREE.MeshStandardMaterial
  }
}

export function Apart4(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/apart4.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062.geometry}
        material={materials['Material.340']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_1.geometry}
        material={materials['Material.341']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_2.geometry}
        material={materials['Material.342']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_3.geometry}
        material={materials['Material.343']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_4.geometry}
        material={materials['Material.344']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_5.geometry}
        material={materials['Material.345']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_6.geometry}
        material={materials['Material.346']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062_7.geometry}
        material={materials['Material.355']}
      />
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/apart4.glb')
