/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube066: THREE.Mesh
    Cube066_1: THREE.Mesh
    Cube066_2: THREE.Mesh
    Cube066_3: THREE.Mesh
    Cube066_4: THREE.Mesh
    Cube066_5: THREE.Mesh
    Cube066_6: THREE.Mesh
  }
  materials: {
    ['Material.334']: THREE.MeshStandardMaterial
    ['Material.335']: THREE.MeshStandardMaterial
    ['Material.336']: THREE.MeshStandardMaterial
    ['Material.337']: THREE.MeshStandardMaterial
    ['Material.338']: THREE.MeshStandardMaterial
    ['Material.339']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
  }
}

export function Apart2(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/apart2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066.geometry}
        material={materials['Material.334']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066_1.geometry}
        material={materials['Material.335']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066_2.geometry}
        material={materials['Material.336']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066_3.geometry}
        material={materials['Material.337']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066_4.geometry}
        material={materials['Material.338']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066_5.geometry}
        material={materials['Material.339']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066_6.geometry}
        material={materials['Material.012']}
      />
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/apart2.glb')
