/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube047: THREE.Mesh
    Cube047_1: THREE.Mesh
    Cube047_2: THREE.Mesh
  }
  materials: {
    ['Material.174']: THREE.MeshStandardMaterial
    ['Material.175']: THREE.MeshStandardMaterial
    ['Material.176']: THREE.MeshStandardMaterial
  }
}

export function CarBlue(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/cars/carblue.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.929, 1.682]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube047.geometry}
          material={materials['Material.174']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube047_1.geometry}
          material={materials['Material.175']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube047_2.geometry}
          material={materials['Material.176']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/cars/carblue.glb')
