/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube059: THREE.Mesh
    Cube059_1: THREE.Mesh
    Cube059_2: THREE.Mesh
    Cube059_3: THREE.Mesh
    Cube059_4: THREE.Mesh
    Cube059_5: THREE.Mesh
  }
  materials: {
    ['Material.259']: THREE.MeshStandardMaterial
    ['Material.260']: THREE.MeshStandardMaterial
    ['Material.261']: THREE.MeshStandardMaterial
    ['Material.262']: THREE.MeshStandardMaterial
    ['Material.263']: THREE.MeshStandardMaterial
    ['Material.264']: THREE.MeshStandardMaterial
  }
}

export function CarFireFighter(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/cars/carfirefighter.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.929, 1.682]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059.geometry}
          material={materials['Material.259']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_1.geometry}
          material={materials['Material.260']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_2.geometry}
          material={materials['Material.261']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_3.geometry}
          material={materials['Material.262']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_4.geometry}
          material={materials['Material.263']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_5.geometry}
          material={materials['Material.264']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/cars/carfirefighter.glb')
