/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube050: THREE.Mesh
    Cube050_1: THREE.Mesh
    Cube050_2: THREE.Mesh
  }
  materials: {
    ['Material.180']: THREE.MeshStandardMaterial
    ['Material.181']: THREE.MeshStandardMaterial
    ['Material.182']: THREE.MeshStandardMaterial
  }
}

export function CarGreen(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/cars/cargreen.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.929, 1.682]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050.geometry}
          material={materials['Material.180']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_1.geometry}
          material={materials['Material.181']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_2.geometry}
          material={materials['Material.182']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/cars/cargreen.glb')
