/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cylinder013: THREE.Mesh
    Cylinder013_1: THREE.Mesh
    Cylinder013_2: THREE.Mesh
    Cylinder013_3: THREE.Mesh
    Cylinder013_4: THREE.Mesh
    Cylinder013_5: THREE.Mesh
  }
  materials: {
    ['Material.265']: THREE.MeshStandardMaterial
    ['Material.266']: THREE.MeshStandardMaterial
    ['Material.267']: THREE.MeshStandardMaterial
    ['Material.268']: THREE.MeshStandardMaterial
    ['Material.269']: THREE.MeshStandardMaterial
    ['Material.270']: THREE.MeshStandardMaterial
  }
}

export function CarPolice(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/cars/carpolice.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.929, 1.682]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={materials['Material.265']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials['Material.266']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_2.geometry}
          material={materials['Material.267']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_3.geometry}
          material={materials['Material.268']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_4.geometry}
          material={materials['Material.269']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_5.geometry}
          material={materials['Material.270']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/cars/carpolice.glb')
