/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube015: THREE.Mesh
    Cube015_1: THREE.Mesh
    Cube015_2: THREE.Mesh
  }
  materials: {
    ['Material.165']: THREE.MeshStandardMaterial
    ['Material.166']: THREE.MeshStandardMaterial
    ['Material.167']: THREE.MeshStandardMaterial
  }
}

export function CarRed(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/cars/carred.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.929, 1.682]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials['Material.165']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials['Material.166']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_2.geometry}
          material={materials['Material.167']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/cars/carred.glb')
