/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube049: THREE.Mesh
    Cube049_1: THREE.Mesh
    Cube049_2: THREE.Mesh
  }
  materials: {
    ['Material.177']: THREE.MeshStandardMaterial
    ['Material.178']: THREE.MeshStandardMaterial
    ['Material.179']: THREE.MeshStandardMaterial
  }
}

export function CarYellow(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/cars/caryellow.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.929, 1.682]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049.geometry}
          material={materials['Material.177']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049_1.geometry}
          material={materials['Material.178']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049_2.geometry}
          material={materials['Material.179']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/cars/caryellow.glb')
