/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    electric: THREE.Mesh
  }
  materials: {
    ['Material.146']: THREE.MeshStandardMaterial
  }
}

export function Electric(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/electric.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.electric.geometry}
        material={materials['Material.146']}
        position={[0, 0, 0.062]}
      />
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/electric.glb')
