/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube044: THREE.Mesh
    Cube044_1: THREE.Mesh
    Cube044_2: THREE.Mesh
    Cube044_3: THREE.Mesh
    Cube044_4: THREE.Mesh
    Cube044_5: THREE.Mesh
    Cube044_6: THREE.Mesh
    Cube044_7: THREE.Mesh
  }
  materials: {
    ['Material.137']: THREE.MeshStandardMaterial
    ['Material.130']: THREE.MeshStandardMaterial
    ['Material.131']: THREE.MeshStandardMaterial
    ['Material.132']: THREE.MeshStandardMaterial
    ['Material.133']: THREE.MeshStandardMaterial
    ['Material.134']: THREE.MeshStandardMaterial
    ['Material.135']: THREE.MeshStandardMaterial
    ['Material.136']: THREE.MeshStandardMaterial
  }
}

export function Factory1(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/factory1.glb') as unknown as GLTFResult
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials['Material.137']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_1.geometry}
        material={materials['Material.130']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_2.geometry}
        material={materials['Material.131']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_3.geometry}
        material={materials['Material.132']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_4.geometry}
        material={materials['Material.133']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_5.geometry}
        material={materials['Material.134']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_6.geometry}
        material={materials['Material.135']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_7.geometry}
        material={materials['Material.136']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/factory1.glb')