/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube046: THREE.Mesh
    Cube046_1: THREE.Mesh
    Cube046_2: THREE.Mesh
    Cube046_3: THREE.Mesh
    Cube046_4: THREE.Mesh
    Cube046_5: THREE.Mesh
    Cube046_6: THREE.Mesh
    Cube046_7: THREE.Mesh
  }
  materials: {
    ['Material.145']: THREE.MeshStandardMaterial
    ['Material.138']: THREE.MeshStandardMaterial
    ['Material.139']: THREE.MeshStandardMaterial
    ['Material.140']: THREE.MeshStandardMaterial
    ['Material.141']: THREE.MeshStandardMaterial
    ['Material.142']: THREE.MeshStandardMaterial
    ['Material.143']: THREE.MeshStandardMaterial
    ['Material.144']: THREE.MeshStandardMaterial
  }
}

export function Factory2(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/factory2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials['Material.145']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_1.geometry}
        material={materials['Material.138']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_2.geometry}
        material={materials['Material.139']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_3.geometry}
        material={materials['Material.140']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_4.geometry}
        material={materials['Material.141']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_5.geometry}
        material={materials['Material.142']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_6.geometry}
        material={materials['Material.143']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_7.geometry}
        material={materials['Material.144']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/factory2.glb')