/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube077: THREE.Mesh
    Cube077_1: THREE.Mesh
    Cube077_2: THREE.Mesh
    Cube077_3: THREE.Mesh
    Cube077_4: THREE.Mesh
    Cube077_5: THREE.Mesh
    Cube077_6: THREE.Mesh
    Cube077_7: THREE.Mesh
  }
  materials: {
    ['Material.378']: THREE.MeshStandardMaterial
    ['Material.379']: THREE.MeshStandardMaterial
    ['Material.380']: THREE.MeshStandardMaterial
    ['Material.381']: THREE.MeshStandardMaterial
    ['Material.383']: THREE.MeshStandardMaterial
    ['Material.384']: THREE.MeshStandardMaterial
    ['Material.385']: THREE.MeshStandardMaterial
    ['Material.377']: THREE.MeshStandardMaterial
  }
}

export function Factory3(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/factory3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.05, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077.geometry}
          material={materials['Material.378']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_1.geometry}
          material={materials['Material.379']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_2.geometry}
          material={materials['Material.380']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_3.geometry}
          material={materials['Material.381']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_4.geometry}
          material={materials['Material.383']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_5.geometry}
          material={materials['Material.384']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_6.geometry}
          material={materials['Material.385']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_7.geometry}
          material={materials['Material.377']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/factory3.glb')
