/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cylinder014: THREE.Mesh
    Cylinder014_1: THREE.Mesh
  }
  materials: {
    ['Material.200']: THREE.MeshStandardMaterial
    ['Material.199']: THREE.MeshStandardMaterial
  }
}

export function Fauntain(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/natures/fauntain.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.042, -0.002, -0.233]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014.geometry}
          material={materials['Material.200']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_1.geometry}
          material={materials['Material.199']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/natures/fauntain.glb')
