/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube053: THREE.Mesh
    Cube053_1: THREE.Mesh
    Cube053_2: THREE.Mesh
    Cube053_3: THREE.Mesh
    Cube053_4: THREE.Mesh
    Cube053_5: THREE.Mesh
    Cube053_6: THREE.Mesh
    Cube053_7: THREE.Mesh
  }
  materials: {
    ['Material.258']: THREE.MeshStandardMaterial
    ['Material.251']: THREE.MeshStandardMaterial
    ['Material.252']: THREE.MeshStandardMaterial
    ['Material.253']: THREE.MeshStandardMaterial
    ['Material.254']: THREE.MeshStandardMaterial
    ['Material.255']: THREE.MeshStandardMaterial
    ['Material.256']: THREE.MeshStandardMaterial
    ['Material.257']: THREE.MeshStandardMaterial
  }
}

export function FireFighter(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/firefighter.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={materials['Material.258']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_1.geometry}
        material={materials['Material.251']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_2.geometry}
        material={materials['Material.252']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_3.geometry}
        material={materials['Material.253']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_4.geometry}
        material={materials['Material.254']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_5.geometry}
        material={materials['Material.255']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_6.geometry}
        material={materials['Material.256']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_7.geometry}
        material={materials['Material.257']}
      />
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/firefighter.glb')
