/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube055: THREE.Mesh
    Cube055_1: THREE.Mesh
    Cube055_2: THREE.Mesh
    Cube055_3: THREE.Mesh
    Cube055_4: THREE.Mesh
    Cube055_5: THREE.Mesh
    Cube055_6: THREE.Mesh
    Cube055_7: THREE.Mesh
    Cube055_8: THREE.Mesh
  }
  materials: {
    ['Material.186']: THREE.MeshStandardMaterial
    ['Material.173']: THREE.MeshStandardMaterial
    ['Material.171']: THREE.MeshStandardMaterial
    ['Material.172']: THREE.MeshStandardMaterial
    ['Material.183']: THREE.MeshStandardMaterial
    ['Material.170']: THREE.MeshStandardMaterial
    ['Material.184']: THREE.MeshStandardMaterial
    ['Material.169']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
}

export function Garbage(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/garbage.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055.geometry}
        material={materials['Material.186']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_1.geometry}
        material={materials['Material.173']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_2.geometry}
        material={materials['Material.171']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_3.geometry}
        material={materials['Material.172']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_4.geometry}
        material={materials['Material.183']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_5.geometry}
        material={materials['Material.170']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_6.geometry}
        material={materials['Material.184']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_7.geometry}
        material={materials['Material.169']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_8.geometry}
        material={materials['Material.006']}
      />
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/garbage.glb')
