/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube045: THREE.Mesh
    Cube045_1: THREE.Mesh
    Cube045_2: THREE.Mesh
    Cube045_3: THREE.Mesh
    Cube045_4: THREE.Mesh
    Cube045_5: THREE.Mesh
    Cube045_6: THREE.Mesh
    Cube045_7: THREE.Mesh
    Cube045_8: THREE.Mesh
  }
  materials: {
    ['Material.158']: THREE.MeshStandardMaterial
    ['Material.159']: THREE.MeshStandardMaterial
    ['Material.160']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.153']: THREE.MeshStandardMaterial
    ['Material.154']: THREE.MeshStandardMaterial
    ['Material.155']: THREE.MeshStandardMaterial
    ['Material.156']: THREE.MeshStandardMaterial
    ['Material.157']: THREE.MeshStandardMaterial
  }
}

export function Grass(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/natures/grass.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.013, 0, -0.751]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045.geometry}
          material={materials['Material.158']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_1.geometry}
          material={materials['Material.159']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_2.geometry}
          material={materials['Material.160']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_3.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_4.geometry}
          material={materials['Material.153']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_5.geometry}
          material={materials['Material.154']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_6.geometry}
          material={materials['Material.155']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_7.geometry}
          material={materials['Material.156']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_8.geometry}
          material={materials['Material.157']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/natures/grass.glb')
