/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube058: THREE.Mesh
    Cube058_1: THREE.Mesh
    Cube058_2: THREE.Mesh
  }
  materials: {
    ['Material.248']: THREE.MeshStandardMaterial
    ['Material.249']: THREE.MeshStandardMaterial
    ['Material.250']: THREE.MeshStandardMaterial
  }
}

export function Hospital(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/hospital.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.002, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058.geometry}
          material={materials['Material.248']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058_1.geometry}
          material={materials['Material.249']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058_2.geometry}
          material={materials['Material.250']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/hospital.glb')
