/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube026: THREE.Mesh
    Cube026_1: THREE.Mesh
    Cube026_2: THREE.Mesh
    Cube026_3: THREE.Mesh
    Cube026_4: THREE.Mesh
    Cube026_5: THREE.Mesh
    Cube026_6: THREE.Mesh
    Cube026_7: THREE.Mesh
    Cube026_8: THREE.Mesh
    Cube026_9: THREE.Mesh
    Cube026_10: THREE.Mesh
  }
  materials: {
    ['Material.109']: THREE.MeshStandardMaterial
    ['Material.108']: THREE.MeshStandardMaterial
    ['Material.107']: THREE.MeshStandardMaterial
    ['Material.106']: THREE.MeshStandardMaterial
    ['Material.105']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.103']: THREE.MeshStandardMaterial
    ['Material.102']: THREE.MeshStandardMaterial
    ['Material.101']: THREE.MeshStandardMaterial
    ['Material.068']: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
  }
}

export function House2(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/house2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.5, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials['Material.109']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials['Material.108']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_2.geometry}
          material={materials['Material.107']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_3.geometry}
          material={materials['Material.106']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_4.geometry}
          material={materials['Material.105']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_5.geometry}
          material={materials['Material.104']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_6.geometry}
          material={materials['Material.103']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_7.geometry}
          material={materials['Material.102']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_8.geometry}
          material={materials['Material.101']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_9.geometry}
          material={materials['Material.068']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_10.geometry}
          material={materials['Material.063']}
        >
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/house2.glb')