/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube042: THREE.Mesh
    Cube042_1: THREE.Mesh
    Cube042_2: THREE.Mesh
    Cube042_3: THREE.Mesh
    Cube042_4: THREE.Mesh
    Cube042_5: THREE.Mesh
    Cube042_6: THREE.Mesh
    Cube042_7: THREE.Mesh
    Cube042_8: THREE.Mesh
    Cube042_9: THREE.Mesh
  }
  materials: {
    ['Material.113']: THREE.MeshStandardMaterial
    ['Material.115']: THREE.MeshStandardMaterial
    ['Material.116']: THREE.MeshStandardMaterial
    ['Material.114']: THREE.MeshStandardMaterial
    ['Material.117']: THREE.MeshStandardMaterial
    ['Material.118']: THREE.MeshStandardMaterial
    ['Material.119']: THREE.MeshStandardMaterial
    ['Material.110']: THREE.MeshStandardMaterial
    ['Material.111']: THREE.MeshStandardMaterial
    ['Material.112']: THREE.MeshStandardMaterial
  }
}

export function House3(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/house3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials['Material.113']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_1.geometry}
        material={materials['Material.115']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_2.geometry}
        material={materials['Material.116']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_3.geometry}
        material={materials['Material.114']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_4.geometry}
        material={materials['Material.117']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_5.geometry}
        material={materials['Material.118']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_6.geometry}
        material={materials['Material.119']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_7.geometry}
        material={materials['Material.110']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_8.geometry}
        material={materials['Material.111']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_9.geometry}
        material={materials['Material.112']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/house3.glb')