/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF, Outlines } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube033_1: THREE.Mesh
    Cube033_2: THREE.Mesh
    Cube033_3: THREE.Mesh
    Cube033_4: THREE.Mesh
    Cube033_5: THREE.Mesh
    Cube033_6: THREE.Mesh
    Cube033_7: THREE.Mesh
    Cube033_8: THREE.Mesh
    Cube033_9: THREE.Mesh
    Cube033_10: THREE.Mesh
    Cube033_11: THREE.Mesh
  }
  materials: {
    ['Material.082']: THREE.MeshStandardMaterial
    ['Material.083']: THREE.MeshStandardMaterial
    ['Material.081']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.079']: THREE.MeshStandardMaterial
    ['Material.078']: THREE.MeshStandardMaterial
    ['Material.077']: THREE.MeshStandardMaterial
    ['Material.076']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.075']: THREE.MeshStandardMaterial
  }
}

export function House1(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/house1.glb') as unknown as GLTFResult;
  
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.5, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_1.geometry}
          material={materials['Material.082']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_2.geometry}
          material={materials['Material.083']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_3.geometry}
          material={materials['Material.081']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_4.geometry}
          material={materials['Material.080']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_5.geometry}
          material={materials['Material.079']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_6.geometry}
          material={materials['Material.078']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_7.geometry}
          material={materials['Material.077']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_8.geometry}
          material={materials['Material.076']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_9.geometry}
          material={materials['Material.074']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_10.geometry}
          material={materials['Material.073']}
        >
        </mesh>
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_11.geometry}
          material={materials['Material.075']}
        >
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('/games/citybuilder/models/buildings/house1.glb');