/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube014: THREE.Mesh
    Cube014_1: THREE.Mesh
    Cube014_2: THREE.Mesh
    Cube014_3: THREE.Mesh
  }
  materials: {
    ['Material.161']: THREE.MeshStandardMaterial
    ['Material.162']: THREE.MeshStandardMaterial
    ['Material.163']: THREE.MeshStandardMaterial
    ['Material.164']: THREE.MeshStandardMaterial
  }
}

export function Maps(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/maps/map.glb') as unknown as GLTFResult
  return (
    <group {...props} position={[640, 0, 640]} dispose={null}>
      <group position={[0, -0.5, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials['Material.161']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials['Material.162']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_2.geometry}
          material={materials['Material.163']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_3.geometry}
          material={materials['Material.164']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/maps/map.glb')
