/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube038: THREE.Mesh
    Cube038_1: THREE.Mesh
    Cube038_2: THREE.Mesh
    Cube038_3: THREE.Mesh
    Cube038_4: THREE.Mesh
  }
  materials: {
    ['Material.062']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
  }
}

export function Market(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/market.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials['Material.062']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_1.geometry}
        material={materials['Material.030']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_2.geometry}
        material={materials['Material.031']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_3.geometry}
        material={materials['Material.032']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_4.geometry}
        material={materials['Material.033']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/market.glb')