/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube052: THREE.Mesh
    Cube052_1: THREE.Mesh
    Cube052_2: THREE.Mesh
    Cube052_3: THREE.Mesh
    Cube052_4: THREE.Mesh
    Cube052_5: THREE.Mesh
  }
  materials: {
    ['Material.242']: THREE.MeshStandardMaterial
    ['Material.243']: THREE.MeshStandardMaterial
    ['Material.244']: THREE.MeshStandardMaterial
    ['Material.245']: THREE.MeshStandardMaterial
    ['Material.246']: THREE.MeshStandardMaterial
    ['Material.247']: THREE.MeshStandardMaterial
  }
}

export function Police(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/police.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.17, -0.002, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052.geometry}
          material={materials['Material.242']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_1.geometry}
          material={materials['Material.243']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_2.geometry}
          material={materials['Material.244']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_3.geometry}
          material={materials['Material.245']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_4.geometry}
          material={materials['Material.246']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_5.geometry}
          material={materials['Material.247']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/police.glb')
