/*
Auto-generated by: [https://github.com/pmndrs/gltfjsx](https://github.com/pmndrs/gltfjsx)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube035: THREE.Mesh
    Cube035_1: THREE.Mesh
    Cube035_2: THREE.Mesh
    Cube035_3: THREE.Mesh
    Cube035_4: THREE.Mesh
  }
  materials: {
    ['Material.092']: THREE.MeshStandardMaterial
    ['Material.091']: THREE.MeshStandardMaterial
    ['Material.090']: THREE.MeshStandardMaterial
    ['Material.089']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
  }
}

export function RoadStraight(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/roads/road1.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.5, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials['Material.092']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_1.geometry}
          material={materials['Material.091']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_2.geometry}
          material={materials['Material.090']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_3.geometry}
          material={materials['Material.089']}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_4.geometry}
          material={materials['Material.088']}
        >
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/roads/road1.glb')