/*
Auto-generated by: [https://github.com/pmndrs/gltfjsx](https://github.com/pmndrs/gltfjsx)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube036: THREE.Mesh
    Cube036_1: THREE.Mesh
    Cube036_2: THREE.Mesh
    Cube036_3: THREE.Mesh
  }
  materials: {
    ['Material.093']: THREE.MeshStandardMaterial
    ['Material.094']: THREE.MeshStandardMaterial
    ['Material.095']: THREE.MeshStandardMaterial
    ['Material.096']: THREE.MeshStandardMaterial
  }
}

export function RoadTee(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/roads/road3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials['Material.093']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036_1.geometry}
        material={materials['Material.094']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036_2.geometry}
        material={materials['Material.095']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036_3.geometry}
        material={materials['Material.096']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/roads/road3.glb')