/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube037: THREE.Mesh
    Cube037_1: THREE.Mesh
    Cube037_2: THREE.Mesh
    Cube037_3: THREE.Mesh
  }
  materials: {
    ['Material.097']: THREE.MeshStandardMaterial
    ['Material.098']: THREE.MeshStandardMaterial
    ['Material.099']: THREE.MeshStandardMaterial
    ['Material.100']: THREE.MeshStandardMaterial
  }
}

export function RoadCrossroad(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/roads/road4.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials['Material.097']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037_1.geometry}
        material={materials['Material.098']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037_2.geometry}
        material={materials['Material.099']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037_3.geometry}
        material={materials['Material.100']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/roads/road4.glb')