/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube034: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube034_2: THREE.Mesh
    Cube034_3: THREE.Mesh
  }
  materials: {
    ['Material.087']: THREE.MeshStandardMaterial
    ['Material.086']: THREE.MeshStandardMaterial
    ['Material.084']: THREE.MeshStandardMaterial
    ['Material.085']: THREE.MeshStandardMaterial
  }
}

export function RoadCorner(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/roads/road2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials['Material.087']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034_1.geometry}
        material={materials['Material.086']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034_2.geometry}
        material={materials['Material.084']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034_3.geometry}
        material={materials['Material.085']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/roads/road2.glb')