/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube063: THREE.Mesh
    Cube063_1: THREE.Mesh
    Cube063_2: THREE.Mesh
    Cube063_3: THREE.Mesh
    Cube063_4: THREE.Mesh
    Cube063_5: THREE.Mesh
    Cube063_6: THREE.Mesh
    Cube063_7: THREE.Mesh
    Cube063_8: THREE.Mesh
    Cube063_9: THREE.Mesh
    Cube063_10: THREE.Mesh
    Cube063_11: THREE.Mesh
    Cube063_12: THREE.Mesh
    Cube063_13: THREE.Mesh
    Cube063_14: THREE.Mesh
    Cube063_15: THREE.Mesh
  }
  materials: {
    ['Material.323']: THREE.MeshStandardMaterial
    ['Material.324']: THREE.MeshStandardMaterial
    ['Material.325']: THREE.MeshStandardMaterial
    ['Material.326']: THREE.MeshStandardMaterial
    ['Material.327']: THREE.MeshStandardMaterial
    ['Material.288']: THREE.MeshStandardMaterial
    ['Material.289']: THREE.MeshStandardMaterial
    ['Material.290']: THREE.MeshStandardMaterial
    ['Material.287']: THREE.MeshStandardMaterial
    ['Material.291']: THREE.MeshStandardMaterial
    ['Material.285']: THREE.MeshStandardMaterial
    ['Material.286']: THREE.MeshStandardMaterial
    ['Material.322']: THREE.MeshStandardMaterial
    ['Material.317']: THREE.MeshStandardMaterial
    ['Material.318']: THREE.MeshStandardMaterial
    ['Material.319']: THREE.MeshStandardMaterial
  }
}

export function SchoolHigh(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/school-high.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.002, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063.geometry}
          material={materials['Material.323']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_1.geometry}
          material={materials['Material.324']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_2.geometry}
          material={materials['Material.325']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_3.geometry}
          material={materials['Material.326']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_4.geometry}
          material={materials['Material.327']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_5.geometry}
          material={materials['Material.288']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_6.geometry}
          material={materials['Material.289']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_7.geometry}
          material={materials['Material.290']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_8.geometry}
          material={materials['Material.287']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_9.geometry}
          material={materials['Material.291']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_10.geometry}
          material={materials['Material.285']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_11.geometry}
          material={materials['Material.286']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_12.geometry}
          material={materials['Material.322']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_13.geometry}
          material={materials['Material.317']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_14.geometry}
          material={materials['Material.318']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_15.geometry}
          material={materials['Material.319']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/school-high.glb')
