/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube068: THREE.Mesh
    Cube068_1: THREE.Mesh
    Cube068_2: THREE.Mesh
    Cube068_3: THREE.Mesh
    Cube068_4: THREE.Mesh
    Cube068_5: THREE.Mesh
    Cube068_6: THREE.Mesh
    Cube068_7: THREE.Mesh
    Cube068_8: THREE.Mesh
    Cube068_9: THREE.Mesh
  }
  materials: {
    ['Material.281']: THREE.MeshStandardMaterial
    ['Material.272']: THREE.MeshStandardMaterial
    ['Material.273']: THREE.MeshStandardMaterial
    ['Material.274']: THREE.MeshStandardMaterial
    ['Material.275']: THREE.MeshStandardMaterial
    ['Material.276']: THREE.MeshStandardMaterial
    ['Material.277']: THREE.MeshStandardMaterial
    ['Material.279']: THREE.MeshStandardMaterial
    ['Material.278']: THREE.MeshStandardMaterial
    ['Material.280']: THREE.MeshStandardMaterial
  }
}

export function SchoolElementary(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/school-elementary.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.002, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068.geometry}
          material={materials['Material.281']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_1.geometry}
          material={materials['Material.272']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_2.geometry}
          material={materials['Material.273']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_3.geometry}
          material={materials['Material.274']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_4.geometry}
          material={materials['Material.275']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_5.geometry}
          material={materials['Material.276']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_6.geometry}
          material={materials['Material.277']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_7.geometry}
          material={materials['Material.279']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_8.geometry}
          material={materials['Material.278']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_9.geometry}
          material={materials['Material.280']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/school-elementary.glb')
