/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Cube061: THREE.Mesh
    Cube061_1: THREE.Mesh
    Cube061_2: THREE.Mesh
    Cube061_3: THREE.Mesh
    Cube061_4: THREE.Mesh
    Cube061_5: THREE.Mesh
    Cube061_6: THREE.Mesh
    Cube061_7: THREE.Mesh
    Cube061_8: THREE.Mesh
    Cube061_9: THREE.Mesh
    Cube061_10: THREE.Mesh
    Cube061_11: THREE.Mesh
    Cube061_12: THREE.Mesh
    Cube061_13: THREE.Mesh
    Cube061_14: THREE.Mesh
    Cube061_15: THREE.Mesh
    Cube061_16: THREE.Mesh
    Cube061_17: THREE.Mesh
  }
  materials: {
    ['Material.282']: THREE.MeshStandardMaterial
    ['Material.283']: THREE.MeshStandardMaterial
    ['Material.284']: THREE.MeshStandardMaterial
    ['Material.285']: THREE.MeshStandardMaterial
    ['Material.286']: THREE.MeshStandardMaterial
    ['Material.287']: THREE.MeshStandardMaterial
    ['Material.292']: THREE.MeshStandardMaterial
    ['Material.293']: THREE.MeshStandardMaterial
    ['Material.294']: THREE.MeshStandardMaterial
    ['Material.295']: THREE.MeshStandardMaterial
    ['Material.296']: THREE.MeshStandardMaterial
    ['Material.297']: THREE.MeshStandardMaterial
    ['Material.298']: THREE.MeshStandardMaterial
    ['Material.299']: THREE.MeshStandardMaterial
    ['Material.307']: THREE.MeshStandardMaterial
    ['Material.308']: THREE.MeshStandardMaterial
    ['Material.309']: THREE.MeshStandardMaterial
    ['Material.321']: THREE.MeshStandardMaterial
  }
}

export function SchoolJunior(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/school-junior.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.002, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061.geometry}
          material={materials['Material.282']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_1.geometry}
          material={materials['Material.283']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_2.geometry}
          material={materials['Material.284']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_3.geometry}
          material={materials['Material.285']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_4.geometry}
          material={materials['Material.286']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_5.geometry}
          material={materials['Material.287']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_6.geometry}
          material={materials['Material.292']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_7.geometry}
          material={materials['Material.293']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_8.geometry}
          material={materials['Material.294']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_9.geometry}
          material={materials['Material.295']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_10.geometry}
          material={materials['Material.296']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_11.geometry}
          material={materials['Material.297']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_12.geometry}
          material={materials['Material.298']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_13.geometry}
          material={materials['Material.299']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_14.geometry}
          material={materials['Material.307']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_15.geometry}
          material={materials['Material.308']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_16.geometry}
          material={materials['Material.309']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_17.geometry}
          material={materials['Material.321']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/school-junior.glb')
