/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube073: THREE.Mesh
    Cube073_1: THREE.Mesh
    Cube073_2: THREE.Mesh
    Cube073_3: THREE.Mesh
    Cube073_4: THREE.Mesh
    Cube073_5: THREE.Mesh
    Cube073_6: THREE.Mesh
    Cube073_7: THREE.Mesh
  }
  materials: {
    ['Material.364']: THREE.MeshStandardMaterial
    ['Material.365']: THREE.MeshStandardMaterial
    ['Material.366']: THREE.MeshStandardMaterial
    ['Material.367']: THREE.MeshStandardMaterial
    ['Material.368']: THREE.MeshStandardMaterial
    ['Material.373']: THREE.MeshStandardMaterial
    ['Material.374']: THREE.MeshStandardMaterial
    ['Material.376']: THREE.MeshStandardMaterial
  }
}

export function Shop(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/shop.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.05, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073.geometry}
          material={materials['Material.364']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_1.geometry}
          material={materials['Material.365']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_2.geometry}
          material={materials['Material.366']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_3.geometry}
          material={materials['Material.367']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_4.geometry}
          material={materials['Material.368']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_5.geometry}
          material={materials['Material.373']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_6.geometry}
          material={materials['Material.374']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_7.geometry}
          material={materials['Material.376']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/shop.glb')
