/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube070: THREE.Mesh
    Cube070_1: THREE.Mesh
    Cube070_2: THREE.Mesh
    Cube070_3: THREE.Mesh
    Cube070_4: THREE.Mesh
    Cube070_5: THREE.Mesh
    Cube070_6: THREE.Mesh
  }
  materials: {
    ['Material.357']: THREE.MeshStandardMaterial
    ['Material.358']: THREE.MeshStandardMaterial
    ['Material.359']: THREE.MeshStandardMaterial
    ['Material.360']: THREE.MeshStandardMaterial
    ['Material.361']: THREE.MeshStandardMaterial
    ['Material.362']: THREE.MeshStandardMaterial
    ['Material.363']: THREE.MeshStandardMaterial
  }
}

export function SuperMarket(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/supermarket.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.05, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070.geometry}
          material={materials['Material.357']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_1.geometry}
          material={materials['Material.358']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_2.geometry}
          material={materials['Material.359']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_3.geometry}
          material={materials['Material.360']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_4.geometry}
          material={materials['Material.361']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_5.geometry}
          material={materials['Material.362']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_6.geometry}
          material={materials['Material.363']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/supermarket.glb')
