/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube051: THREE.Mesh
    Cube051_1: THREE.Mesh
    Cube051_2: THREE.Mesh
    Cube051_3: THREE.Mesh
    Cube051_4: THREE.Mesh
    Cube051_5: THREE.Mesh
    Cube051_6: THREE.Mesh
    Cube051_7: THREE.Mesh
    Cube051_8: THREE.Mesh
    Cube051_9: THREE.Mesh
    Cube051_10: THREE.Mesh
  }
  materials: {
    ['Material.187']: THREE.MeshStandardMaterial
    ['Material.185']: THREE.MeshStandardMaterial
    ['Material.188']: THREE.MeshStandardMaterial
    ['Material.189']: THREE.MeshStandardMaterial
    ['Material.190']: THREE.MeshStandardMaterial
    ['Material.191']: THREE.MeshStandardMaterial
    ['Material.192']: THREE.MeshStandardMaterial
    ['Material.193']: THREE.MeshStandardMaterial
    ['Material.194']: THREE.MeshStandardMaterial
    ['Material.195']: THREE.MeshStandardMaterial
    ['Material.196']: THREE.MeshStandardMaterial
  }
}

export function Tree1(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/natures/tree1.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.037, -0.024, -0.022]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051.geometry}
          material={materials['Material.187']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_1.geometry}
          material={materials['Material.185']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_2.geometry}
          material={materials['Material.188']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_3.geometry}
          material={materials['Material.189']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_4.geometry}
          material={materials['Material.190']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_5.geometry}
          material={materials['Material.191']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_6.geometry}
          material={materials['Material.192']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_7.geometry}
          material={materials['Material.193']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_8.geometry}
          material={materials['Material.194']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_9.geometry}
          material={materials['Material.195']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_10.geometry}
          material={materials['Material.196']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/natures/tree1.glb')
