/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube054: THREE.Mesh
    Cube054_1: THREE.Mesh
    Cube054_2: THREE.Mesh
    Cube054_3: THREE.Mesh
    Cube054_4: THREE.Mesh
    Cube054_5: THREE.Mesh
    Cube054_6: THREE.Mesh
    Cube054_7: THREE.Mesh
    Cube054_8: THREE.Mesh
    Cube054_9: THREE.Mesh
    Cube054_10: THREE.Mesh
    Cube054_11: THREE.Mesh
    Cube054_12: THREE.Mesh
    Cube054_13: THREE.Mesh
    Cube054_14: THREE.Mesh
    Cube054_15: THREE.Mesh
    Cube054_16: THREE.Mesh
    Cube054_17: THREE.Mesh
    Cube054_18: THREE.Mesh
    Cube054_19: THREE.Mesh
    Cube054_20: THREE.Mesh
    Cube054_21: THREE.Mesh
    Cube054_22: THREE.Mesh
    Cube054_23: THREE.Mesh
    Cube054_24: THREE.Mesh
  }
  materials: {
    ['Material.209']: THREE.MeshStandardMaterial
    ['Material.210']: THREE.MeshStandardMaterial
    ['Material.211']: THREE.MeshStandardMaterial
    ['Material.212']: THREE.MeshStandardMaterial
    ['Material.213']: THREE.MeshStandardMaterial
    ['Material.214']: THREE.MeshStandardMaterial
    ['Material.215']: THREE.MeshStandardMaterial
    ['Material.216']: THREE.MeshStandardMaterial
    ['Material.201']: THREE.MeshStandardMaterial
    ['Material.202']: THREE.MeshStandardMaterial
    ['Material.203']: THREE.MeshStandardMaterial
    ['Material.204']: THREE.MeshStandardMaterial
    ['Material.205']: THREE.MeshStandardMaterial
    ['Material.206']: THREE.MeshStandardMaterial
    ['Material.207']: THREE.MeshStandardMaterial
    ['Material.208']: THREE.MeshStandardMaterial
    ['Material.235']: THREE.MeshStandardMaterial
    ['Material.234']: THREE.MeshStandardMaterial
    ['Material.233']: THREE.MeshStandardMaterial
    ['Material.241']: THREE.MeshStandardMaterial
    ['Material.240']: THREE.MeshStandardMaterial
    ['Material.239']: THREE.MeshStandardMaterial
    ['Material.238']: THREE.MeshStandardMaterial
    ['Material.237']: THREE.MeshStandardMaterial
    ['Material.236']: THREE.MeshStandardMaterial
  }
}

export function Tree2(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/natures/tree2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.649, 0.498, -0.698]} rotation={[-Math.PI, 0.8, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054.geometry}
          material={materials['Material.209']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_1.geometry}
          material={materials['Material.210']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_2.geometry}
          material={materials['Material.211']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_3.geometry}
          material={materials['Material.212']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_4.geometry}
          material={materials['Material.213']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_5.geometry}
          material={materials['Material.214']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_6.geometry}
          material={materials['Material.215']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_7.geometry}
          material={materials['Material.216']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_8.geometry}
          material={materials['Material.201']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_9.geometry}
          material={materials['Material.202']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_10.geometry}
          material={materials['Material.203']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_11.geometry}
          material={materials['Material.204']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_12.geometry}
          material={materials['Material.205']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_13.geometry}
          material={materials['Material.206']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_14.geometry}
          material={materials['Material.207']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_15.geometry}
          material={materials['Material.208']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_16.geometry}
          material={materials['Material.235']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_17.geometry}
          material={materials['Material.234']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_18.geometry}
          material={materials['Material.233']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_19.geometry}
          material={materials['Material.241']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_20.geometry}
          material={materials['Material.240']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_21.geometry}
          material={materials['Material.239']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_22.geometry}
          material={materials['Material.238']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_23.geometry}
          material={materials['Material.237']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_24.geometry}
          material={materials['Material.236']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/natures/tree2.glb')
