/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Outlines, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cube041: THREE.Mesh
    Cube041_1: THREE.Mesh
    Cube041_2: THREE.Mesh
    Cube041_3: THREE.Mesh
    Cube041_4: THREE.Mesh
  }
  materials: {
    ['Material.129']: THREE.MeshStandardMaterial
    ['Material.125']: THREE.MeshStandardMaterial
    ['Material.126']: THREE.MeshStandardMaterial
    ['Material.127']: THREE.MeshStandardMaterial
    ['Material.128']: THREE.MeshStandardMaterial
  }
}

export function Warteg(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/warteg.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials['Material.129']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_1.geometry}
        material={materials['Material.125']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_2.geometry}
        material={materials['Material.126']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_3.geometry}
        material={materials['Material.127']}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_4.geometry}
        material={materials['Material.128']}
      >
      </mesh>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/warteg.glb')