/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'; 

type GLTFResult = GLTF & {
  nodes: {
    Cylinder008: THREE.Mesh
    Cylinder008_1: THREE.Mesh
    Cylinder008_2: THREE.Mesh
    Cylinder008_3: THREE.Mesh
    Cylinder008_4: THREE.Mesh
    Cylinder008_5: THREE.Mesh
  }
  materials: {
    ['Material.147']: THREE.MeshStandardMaterial
    ['Material.148']: THREE.MeshStandardMaterial
    ['Material.149']: THREE.MeshStandardMaterial
    ['Material.150']: THREE.MeshStandardMaterial
    ['Material.151']: THREE.MeshStandardMaterial
    ['Material.152']: THREE.MeshStandardMaterial
  }
}

export function Water(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/games/citybuilder/models/buildings/water.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.135, 0.315, 0.418]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.157}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials['Material.147']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials['Material.148']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_2.geometry}
          material={materials['Material.149']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_3.geometry}
          material={materials['Material.150']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_4.geometry}
          material={materials['Material.151']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_5.geometry}
          material={materials['Material.152']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/games/citybuilder/models/buildings/water.glb')
